# Generated by Django 3.0.8 on 2020-08-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200812_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My Freaking Awesome Blog', max_length=255),
        ),
    ]
