# Generated by Django 3.1.3 on 2020-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201205_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug_title',
            field=models.CharField(default=models.CharField(max_length=255, null=True), max_length=255, null=True, unique=True),
        ),
    ]
