# Generated by Django 3.1.3 on 2020-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201205_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug_title',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
