# Generated by Django 3.1.3 on 2020-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201205_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
